### ISSUE TITLE
Any release planned ?

### ISSUE THREAD

**Issue by pethers** [structurizr/java-extensions#10]
would be nice with a release using 1.3.3 of https://github.com/structurizr/java .

**Comment by simonbrowndotje** [comment]
Do you have any thoughts on whether the version numbers should be kept in sync with the main Java client library? In fact, should the whole of the extensions repo have a single version number?

**Comment by pethers** [comment]
Prefer one repository one release version, but life cycle different from main client library so would not use the same version. But it is just me, happy either way.

**Comment by simonbrowndotje** [comment]
v1.3.4 has been released onto Maven Central.
