### ISSUE TITLE
Replace reflections by classgraph in structurizr-spring

### ISSUE THREAD

**Issue by Riduidel** [structurizr/java-extensions#11]
The second one seems faster than the first one, as it doesn't load the class object but reads the `.class` files. See https://github.com/classgraph/classgraph

**Comment by Riduidel** [comment]
Seems like reflections dependency is added in `structurizr-analysis` and inherited from that module to spring and other ones...

**Comment by Riduidel** [comment]
On typical spring-boot applications, I get quite long reflection tax 

```INFOS: Reflections took 289 ms to scan 261 urls, producing 7 keys and 45 values 
févr. 05, 2020 4:52:39 PM org.reflections.Reflections scan
INFOS: Reflections took 248 ms to scan 261 urls, producing 11 keys and 49 values 
févr. 05, 2020 4:52:39 PM org.reflections.Reflections scan
INFOS: Reflections took 371 ms to scan 261 urls, producing 6 keys and 14 values 
févr. 05, 2020 4:52:39 PM org.reflections.Reflections scan
INFOS: Reflections took 689 ms to scan 261 urls, producing 11 keys and 31 values ```

**Comment by simonbrowndotje** [comment]
I think this should be relatively straightforward, in that you should be able to create a different implementation of the ```TypeRepository``` interface. Here's the Reflections version -> https://github.com/structurizr/java-extensions/blob/master/structurizr-analysis/src/com/structurizr/analysis/DefaultTypeRepository.java

Having said that, I've not looked at classgraph, so I'm not sure if the ```Class``` return types are compatible.

**Comment by Riduidel** [comment]
`AnnotatedMethodComponentFinderStrategy` makes direct use of `ReflectionsUtils` (see [line 104](https://github.com/structurizr/java-extensions/blob/master/structurizr-analysis/src/com/structurizr/analysis/AnnotatedMethodComponentFinderStrategy.java#L104)), well, this just means the refactoring will be just a little longer than what I expected 😅

**Comment by Riduidel** [comment]
After having tried a refactoring, I got no performance benefit from replacing reflections by anything else. So I'll close that issue for now.
