### ISSUE TITLE
Feature request: PlantUMLWriter export for FilteredView

### ISSUE THREAD

**Issue by drazzib** [structurizr/java-extensions#13]
Hi,

I'm trying to export some `FilteredView` using `PlantUMLWriter` but it seems to be a unsupported feature from looking at actual code :

`
workspace.getViews().getSystemLandscapeViews().forEach(v -> write(v, writer));
workspace.getViews().getSystemContextViews().forEach(v -> write(v, writer));
workspace.getViews().getContainerViews().forEach(v -> write(v, writer));
workspace.getViews().getComponentViews().forEach(v -> write(v, writer));
workspace.getViews().getDynamicViews().forEach(v -> write(v, writer));
workspace.getViews().getDeploymentViews().forEach(v -> write(v, writer));
`

It would be great to add export support for `FilteredView` !

Best regards,

**Comment by Riduidel** [comment]
Didn't even knew Structurizr could do that! So I'll implement that now from the doc there https://www.structurizr.com/help/filtered-views

**Comment by simonbrowndotje** [comment]
I'm not sure how much value there is in implementing that to be honest. With the Structurizr service, the filtered views use the layout information of the base view, so that the same elements reside in the same location across multiple views. Since PlantUML does layouts for you, a major benefit of filtered views doesn't exist.

**Comment by Riduidel** [comment]
I'm copy/pasting the issues I'm facing

1. I have to add elements/relationships to my view and the methods I want to call (`View#addElement(...)` and `View#addRelationship(...)`) are protected or (worse) private
2. I cannot guarantee that PlantUML will render elements at the same positoon.
As a consequence, the best thing I can imagine is fully clone the view , *then* mark (by some kind of magic) elements as hiden (the best way I can imagine is color them all with background color)
