### ISSUE TITLE
com.structurizr.io.plantuml.PlantUMLWriter#toStdOut writing one linebreak to much

### ISSUE THREAD

**Issue by mwiede** [structurizr/java-extensions#16]
I wanted to use the output of PlantUMLWriter#toStdOut to pipe it to plantuml/graphviz directly.
Unfortunately the last linebreak is leading to error.

```
...
(2.825 - 139 Mo) 60 Mo - Creating AParentFolderRegular .
(3.905 - 197 Mo) 101 Mo - Creating image 565x274
(4.097 - 197 Mo) 72 Mo - Ok for com.sun.imageio.plugins.png.PNGMetadata
ERROR
0
Empty description
Some diagram description contains errors
```

Of course I can get around this issue easily on my own.

But why not fixing the root cause and replacing println with print?

**Comment by simonbrowndotje** [comment]
The ```toPlantUMLDiagrams``` method (https://github.com/structurizr/java-extensions/blob/master/structurizr-plantuml/src/com/structurizr/io/plantuml/PlantUMLWriter.java#L209) now provides more control, so I'd recommend using that instead of ```toStdOut```.
