### ISSUE TITLE
ComponentFinder using an external package

### ISSUE THREAD

**Issue by henrywilliams96** [structurizr/java-extensions#17]
I'm writing a Structizr application that can take in a directory, and generate diagrams from its source code. From what I can tell, the `ComponentFinder`'s 2nd argument only works with packages within the same project.

In other words, the `ComponentFinder` is in `home/username/Documents/project/`. How might I get it to find components in `home/username/Documents/anotherProject`?

I realise this may be more of a Java question than a Structizr question - apologies if so!

**Comment by simonbrowndotje** [comment]
The 2nd argument is the name of the package that you'd like to run the component finder against, e.g. ```com.mycompany.anotherProject```.

Then, when you run your Structurizr program, you need to put the compiled classes in ```home/username/Documents/anotherProject``` on the [Java classpath](https://en.wikipedia.org/wiki/Classpath_(Java)) of your program in ```home/username/Documents/project/```. Hope that helps!

**Comment by henrywilliams96** [comment]
Thanks Simon!

Some more info on my application: it's an IntelliJ IDEA plugin that aims to automate the detection of Software Systems, Containers etc. on a program.  So, when I use the `ComponentFinder` the program in `anotherProject` won't be compiled yet.  Is there any workaround to this? 

p.s. this is now beyond an "issue" with Structurizr, rather just me trying to work out how to use it in my own application, so of course no worries if there's nothing that can be done!

**Comment by simonbrowndotje** [comment]
You're welcome. Yes, the existing component finder strategies use reflection on the Java bytecode, so the other project would need to be compiled first. I've never built an IDEA plugin, so I'm not sure that I can offer much help. I imagine that you have some options though, including:

1. Trigger a build of the other project (assuming it's a module in the same project).
2. Write your own component finder strategy that parses the Java source code (e.g. perhaps IDEA provides some facilities for this), instead of using the compiled bytecode.

**Comment by henrywilliams96** [comment]
Re option 2 - how does a component finder strategy add relationships between elements? I've been struggling as all of the ``addRelationship`` methods I can see in Structurizr are private, and I can't see at  what point in the component finding process relationships are established.

**Comment by simonbrowndotje** [comment]
There are a number of public ```uses``` methods on the [StaticStructureElement](https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/StaticStructureElement.java) class that you can use to create relationships (the ```Component``` class extends this).

**Comment by henrywilliams96** [comment]
Wow! Not sure how I missed all those. Thanks for your help, Simon.
