### ISSUE TITLE
GitHUb action can't sign artifacts

### ISSUE THREAD

**Issue by Riduidel** [structurizr/java-extensions#26]
It seems like building of structurizr-java-extensions requires some files only @simonbrowndotje has (tyically signatures). It's really not a problem, and I fully understand why. But as I want to get a little more involved in these extensions, I would like to a have a real CI process available.
@simonbrowndotje can you please take a look at the singing gradle extension and see what is required to have it working on GitHub actions ?
Thanks *a lot*

**Comment by simonbrowndotje** [comment]
I changed the Gradle command to just run the default tasks, so the signing isn't executed. That seems to work, although there's a compilation error.
