### ISSUE TITLE
Graphviz autolayout doesn't work well with multiple relations between two elements

### ISSUE THREAD

**Issue by Morozzzko** [structurizr/java-extensions#27]
**Context**: I'm using structurizr 1.3.5 with Kotlin, without [structurizr-kotlin](https://github.com/Catalysts/structurizr-extensions/tree/master/structurizr-kotlin).

I'm trying to create a dynamic view to illustrate a process when a monolith (a container) both writes and consumes events from Kafka. The concrete technology doesn't matter, though.

So, I've got two relationships: 

* Monolith consumes events from Kafka
* Kafka provides events to monolith

I've added them to my Dynamic View, but the resulting diagram is rather disappointing: the arrows overlap each other. See how it looks:

![broken arrows](https://user-images.githubusercontent.com/887264/83051852-37fabe80-a057-11ea-8811-763064f80e07.png)

I've edited the diagram to give you an idea of how I wanted it to look:

![manually adjusted errors](https://user-images.githubusercontent.com/887264/83051803-274a4880-a057-11ea-8fb1-90ef2bcc46b1.png)

I've tried to blame `dot` for this, but the generated dot file and SVG are solid.

Here's the dot:

```dot
digraph {
  graph [splines=polyline,rankdir=TB,ranksep=1.0,nodesep=1.0,fontsize=5]
  node [shape=box,fontsize=5]
  edge []

  subgraph cluster_2 {
    margin=25
    3 [width=1.500000,height=1.000000,fixedsize=true,id=3,label="3: Kafka"]
    4 [width=1.500000,height=1.000000,fixedsize=true,id=4,label="4: Monolith"]
  }
  1 [width=1.500000,height=1.000000,fixedsize=true,id=1,label="1: Customer"]

  1 -> 4 [id=5]
  4 -> 3 [id=6]
  3 -> 4 [id=7]
}
```

Here's the SVG screenshot: 

<img width="457" alt="svg with all the arrows" src="https://user-images.githubusercontent.com/887264/83052043-73958880-a057-11ea-96ce-1df602003d91.png">

So I'm guessing there's something wrong with the autolayout code itself. Any tips on fixing it?

Here's the source code for the workspace:

<details>

```kotlin
    val workspace = Workspace("ArrowTest", "This diagram will fail to draw multiple arrows")

    val model = workspace.model

    val customer = model.addPerson("Customer", "Customer is a person")

    val waffle = model.addSoftwareSystem(Location.Internal, "Waffle", "Waffle factory")

    val kafka = waffle.addContainer("Kafka", "Event streaming", "Apache Kafka")

    val monolith = waffle.addContainer("Monolith", "Sample API server", "Roda")

    customer.uses(monolith, "Grabs waffles from waffle factory directly via API")

    monolith.uses(kafka, "monolith consumes events from a kafka's topic")
    kafka.uses(monolith, "")

    val dynamicDiagram = workspace.views.createDynamicView(waffle, "Arrow demonstration", "It containes two-sided relationship")

    dynamicDiagram.add(customer, "Sends POST request to /api/waffles/orders", monolith)

    dynamicDiagram.add(monolith, "Publishes events to Kafka", kafka)
    dynamicDiagram.add(kafka, "Provides events to consumer", monolith)

    val graphviz = GraphvizAutomaticLayout()
    graphviz.apply(workspace)
```

</details>

UPD: 1 network shows proper arrows, too

![network](https://user-images.githubusercontent.com/887264/83052321-d129d500-a057-11ea-9756-5721d675f202.png)

**Comment by simonbrowndotje** [comment]
We've pushed some updates to the Structurizr renderer, and it should give you this now.

![structurizr-35-Arrow demonstration](https://user-images.githubusercontent.com/1009874/83116184-53031800-a0c3-11ea-9bcb-1f5c17e7e7db.png)

**Comment by Morozzzko** [comment]
Oh, I actually expected it to be a client-side problem. 

Can confirm, it renders well now. Thank you!

**Comment by simonbrowndotje** [comment]
That's great, thanks!
