### ISSUE TITLE
Links between decision records are not working

### ISSUE THREAD

**Issue by jwalter** [structurizr/java-extensions#29]
When I publish my ADRs using https://github.com/structurizr/publish to https://structurizr.com/, the URLs of published decision records ends with ```decisions#%2F:<ID>``` while links between decision records ends with ```decisions#/:<ID>```. The links between records seem to be generated by AdrToolsImporter but I'm not sure where the actual decision record URLs on structurizr.com are generated and I'm not sure which URL format is the correct one.

**Comment by simonbrowndotje** [comment]
I've just released v1.0.2 of the structurizr-publish tool too -> https://github.com/structurizr/publish/releases/tag/v1.0.2
