### ISSUE TITLE
Move C4-PlantUML pencils to standard location

### ISSUE THREAD

**Issue by Riduidel** [structurizr/java-extensions#37]
There is now a PlantUML stdlib owner on GitHub, hosting, well, standard extensions.
On these standard extensions, there is a C4-PlantUML one built from RicardoNiepel base.
It would be good to use it as default.

**Comment by simonbrowndotje** [comment]
It seems some tests are broken.

**Comment by Riduidel** [comment]
Thanks for fixing the tests!
And it seems like there are now deployment and dynamic diagrams support
