### ISSUE TITLE
url attributes not generated in plantuml export

### ISSUE THREAD

**Issue by DaveFoxOpenGI** [structurizr/java-extensions#41]
running 'export' using CLI with  "-format plantuml"  with the test.dsl workspace from the examples folder does not generate any url/links/annotations in the generated puml files. 

The url tags are being parsed - as invalid urls do generate errors .

e.g.
java -jar structurizr-cli-1.6.0.jar export -workspace test.dsl --output out

I was expecting something in either the skinparam the participant definition:

Generated structurizr-Dynamic-sequence.puml snippet:
```
skinparam sequenceParticipant<<1>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #777777
  roundCorner 20
}
...
participant "User\n<size:10>[Person]</size>" as 1 <<1>> #ffffff
```

**Comment by simonbrowndotje** [comment]
Closing this issue for now ... feel free to re-open when needed.
