### ISSUE TITLE
[PlantUML] Allow generating diagram with no title

### ISSUE THREAD

**Issue by MLNW** [structurizr/java-extensions#42]
I am using the generated diagrams in a document where they are captioned separately, e.g., a thesis with a figure environment.

In this case, I do not want to have a title nor a description attached to the diagram, since this will all be contained within the caption.

It is already possible to leave the description blank but when leaving the title blank or setting it specifically to an empty string it is then replaced by the name of the diagram (which is also auto-generated?).
See [the code here](https://github.com/structurizr/java-extensions/blob/master/structurizr-plantuml/src/com/structurizr/io/plantuml/PlantUMLWriter.java#L402).

Would it be possible to make the title optional? Either by ignoring it if it is blank or through a flag to the diagram? Or do you disagree with removing the title within a document where it is also captioned?

**Comment by simonbrowndotje** [comment]
I would personally leave the caption on the diagram, because it stays intact whenever somebody screenshots/copy-pastes the image out of the document and into something like a presentation.

**Comment by MLNW** [comment]
I guess the largest issue I have with this is the large discrepancy between the diagram font and the remaining font within the document.

Also, since the document is a thesis, the diagrams will not be cut from the text for any purpose. The major output will be a printed version.

P.S. Wow, that was a quick reaction 😄

**Comment by simonbrowndotje** [comment]
If your document/diagram generation is automated, you could remove the `title ...` line out of the PlantUML source definitions with a script? Are you using the Structurizr for Java library directly, or the DSL?

**Comment by MLNW** [comment]
I have been using the DSL but am currently experimenting with the Java library directly. The idea is to automate the generation in a way that can be used during a CI/CD pipeline.

Removing the title with a simple call to `sed` should be easy. It just feels a little "hacky" 😉

**Comment by simonbrowndotje** [comment]
Understood ... "hacky" will be quicker for you than making the changes though. 🙂

**Comment by MLNW** [comment]
For anyone looking to use the workaround mentioned above here is a snippet (using Kotlin) that filters out the title line before persisting each diagram to disk:
```kotlin
@OptIn(ExperimentalPathApi::class)
private final fun storeDiagramsOnDisk(views: MutableCollection<View>) {
    val plantUMLWriter = C4PlantUMLWriter()
    val path = Path("build", "resources", "diagrams").also { it.createDirectories() }
    views.forEach {
        val diagram = plantUMLWriter.toString(it)
        val diagramWithoutTitle = diagram.lines()
            .filter { line -> !line.startsWith("title") }
            .joinToString("\n")
        path.resolve("${it.key}.puml").writeText(diagramWithoutTitle, Charsets.UTF_8)
    }
}
```

**Comment by simonbrowndotje** [comment]
The PlantUML writers now have a `setIncludeDiagramMetadata(boolean)` method that provides a way to toggle the diagram title+description on/off.
