### ISSUE TITLE
Person notation

### ISSUE THREAD

**Issue by brunopenso** [structurizr/java-extensions#44]
Hi,

I'm using structurizr for java and everything is generating like it should, but the Person is not generating like a person object but is showing a rounded box. (see image bellow)

I added this code:
```java
Styles styles = views.getConfiguration().getStyles();
styles.addElementStyle(Tags.SOFTWARE_SYSTEM).background("#1168bd").color("#ffffff");
styles.addElementStyle(Tags.PERSON).background("#444444").color("#ffffff").shape(Shape.Person);
```

And I'm creating the output using:
```java
StructurizrPlantUMLWriter plantUMLWriter = new StructurizrPlantUMLWriter();
plantUMLWriter.setUseSequenceDiagrams(false);
Collection<PlantUMLDiagram> diagrams = plantUMLWriter.toPlantUMLDiagrams(workspace);
//more line to generate the file, for example
for (PlantUMLDiagram diagram : diagrams) {
	SourceStringReader reader = new SourceStringReader(diagram.getDefinition());

	FileOutputStream fo = new FileOutputStream(
			new File(outputDir, String.format("%s-%s.svg", workspaceName, diagram.getKey())));
	reader.outputImage(fo, new FileFormatOption(FileFormat.SVG));
	fo.close();
}
```

Today output:
![dsl](https://user-images.githubusercontent.com/1093677/109654198-a9b0ed00-7b40-11eb-90cc-3142fad0b186.png)

**Comment by simonbrowndotje** [comment]
The PlantUML renderers don't support the person shape I'm afraid.

**Comment by brunopenso** [comment]
Hi Simon, thanks for the answer. Do you recommend another lib?

**Comment by simonbrowndotje** [comment]
You can see some examples of how the different tools render diagrams at [https://structurizr.org/#rendering](https://structurizr.org/#rendering) ... the Structurizr cloud service/on-premises installation is the only one that supports a person shape. The `C4PlantUMLWriter` outputs PlantUML that makes use of the C4-PlantUML macros, and does include a person sprite in the box, but it's limited in terms of styling elements.

![jL7DQy8m5B_dhyXwQc5jcUmq65XKja7TP5h6JkNPH0taY-GLzRzVKlKYk_QKnu_VrtkPUWI7lPAfOA_hiqUkPaOZFs567eJkPCzuxoGz85h_KfOEZiLUuA7VzfwxBb8r5frHfPMWer7kaKcnBMVF-If2pR8k5GHZ5w321iOOnksrzRW183HtOqOeQtJK315rzVlLRDgVZyrxMo_U5f_pD2C41KfErsQ7Ht1X6FwCvhVXUWVI](https://user-images.githubusercontent.com/1009874/109817360-c4ab5c00-7c29-11eb-9b00-a14ad94ec896.png)

**Comment by simonbrowndotje** [comment]
Here are the shapes supported by each of the current renderers:

**Structurizr**
![shapes-structurizr](https://user-images.githubusercontent.com/1009874/110113049-72de0f80-7daa-11eb-9cc7-72e164567e98.png)

**StructurizrPlantUMLWriter**
![shapes-plantuml](https://user-images.githubusercontent.com/1009874/110113143-95702880-7daa-11eb-8a3e-46d7b233ef3e.png)

**C4PlantUMLWriter**
![shapes-c4plantuml](https://user-images.githubusercontent.com/1009874/110113161-9bfea000-7daa-11eb-8ff5-ab8bfc7a7a8d.png)

**MermaidWriter**
<img width="566" alt="shapes-mermaid" src="https://user-images.githubusercontent.com/1009874/110113177-9f922700-7daa-11eb-9559-447093d2b3d4.png">
