### ISSUE TITLE
How to setup IDE (VSCode) to contribute code?

### ISSUE THREAD

**Issue by MTomBosch** [structurizr/java-extensions#46]
I am thinking about potentially contributing some changes to this repo but I am struggling to properly setup my VSCode environment with this repo to get proper code completion.

Can you explain how your IDE setup looks like or which IDE you are using for the development?

Thank you

**Comment by simonbrowndotje** [comment]
I use IntelliJ, which allows you to [Open an existing Gradle project﻿](https://www.jetbrains.com/help/idea/gradle.html#gradle_import_project_start). I've never used VS Code as an IDE, so I can't help you there I'm afraid.

**Comment by MTomBosch** [comment]
Ok. Thanks. I was somehow expecting that answer since I saw somewhere in the code a reference to idea ;)
Closing the issue then.
