### ISSUE TITLE
Is it possible to add multple software systems, their containers and their relationships on 1 view, preferably container

### ISSUE THREAD

**Issue by kjellmoens** [structurizr/java-extensions#47]
Hi, 

For the moment, I got this but i can not add the containers to the diagram
I would like to have the BTM software system and the relations from its containers to the containers of isilon.

Thank you,

  Model model = workspace.getModel();

        Person approver = model.addPerson(Location.Internal, "Approver", "");

        SoftwareSystem isilon = model.addSoftwareSystem(Location.Internal, "Isilon FTP", "");
        Container isilonCoda = isilon.addContainer("/coda", "", "Directory");
        Container isilonData = isilon.addContainer("/data", "", "Directory");
        Container isilonSepa = isilon.addContainer("/sepa", "", "Directory");

        SoftwareSystem sterling = model.addSoftwareSystem(Location.Internal, "Sterlin FTP", "");
        Container sterlingCoda = sterling.addContainer("/In/coda", "", "Directory");
        Container sterlingNotif = sterling.addContainer("/In/notif", "", "Directory");
        Container sterlingSepa  = sterling.addContainer("/Out/sepa", "", "Directory");

        SoftwareSystem btm = model.getSoftwareSystemWithName("BTM");
        Container coda = btm.addContainer("Coda", "", "Java, Spring");
        Container sepa = btm.addContainer("Sepa", "", "Java, Spring");
        Container database = btm.addContainer("Database", "", "FTP");
        database.addTags(DATABASE_TAG);

        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        approver.uses(sepa, "approves");

        coda.uses(database, "");
        coda.uses(isilonCoda, "puts");
        coda.uses(isilonData, "puts");
        sepa.uses(isilonSepa, "gets");

        sepa.uses(database, "");
        coda.uses(sterlingCoda, "gets");
        coda.uses(sterlingNotif, "gets");
        sepa.uses(sterlingSepa, "puts");

        // define some views (the diagrams you would like to see)
        ViewSet views = workspace.getViews();

        ContainerView containerView = views.createContainerView(btm, "Containers", "The container diagram for the BTM System.");
       containerView.add(approver);
        containerView.add(isilon);
        containerView.add(sterling);
        containerView.add(isilonCoda);
        containerView.add(isilonData);
        containerView.add(isilonSepa);
        containerView.addAllContainersAndInfluencers();
        containerView.addAllContainers();
        containerView.addDependentSoftwareSystems();

        // add some documentation
        StructurizrDocumentationTemplate template = new StructurizrDocumentationTemplate(workspace);
        template.addContainersSection(btm, Format.Markdown,
                "Here is some context about the software system...\n" +
                        "\n" +
                        "![](embed:SystemContext)");

        return containerView;

**Comment by simonbrowndotje** [comment]
Yes, I've just checked, and the PlantUML writer is ignoring any containers that are not a part of the software system in scope. This is what my quick fix renders:

![image](https://user-images.githubusercontent.com/1009874/111659045-ccabf400-8804-11eb-8a87-983b006e850d.png)

I will do some more testing and include this in the next release.

**Comment by simonbrowndotje** [comment]
v1.6.2 has just been released, which includes this functionality -> https://github.com/structurizr/java-extensions/tree/master/structurizr-plantuml#162-20th-march-2021
