### ISSUE TITLE
Add support for tags in the C4-PlantUML export

### ISSUE THREAD

**Issue by MTomBosch** [structurizr/java-extensions#51]
With the recently introduced support for themes the structurizr cli exporter is really getting better and better. One last bit is missing:
The support for icons (either via the themes) or via some magic that injects plantuml icons via  the defined set of std libraries https://plantuml.com/stdlib.

My idea was to define in the styles the plantuml "icon" to use and then this information is used by the standard/structurizr plantuml exporter to create the elements.

**Comment by MLNW** [comment]
The C4 PlantUML project also allows setting icons from external URLs, e.g. to add the Java icon. It would be great to also allow using those if this feature is implemented.

**Comment by simonbrowndotje** [comment]
PlantUML icons are text-based sprites, rather than PNG files, so they're not particularly compatible out of the box unfortunately. You could always just use the Structurizr renderer. 🙂

**Comment by MTomBosch** [comment]
> 
> 
> PlantUML icons are text-based sprites, rather than PNG files, so they're not particularly compatible out of the box unfortunately. You could always just use the Structurizr renderer. 🙂

Yes, you are right. My focus is not on being able to add any sort of png. Just having means to specify in the dsl somehow the icon information for plantuml so that the plantuml exporter can then make use of this to generate the plantuml files would be "enough". I know this "enough" would be a big feature but if you don't ask you don't get anything ;)

Since only the structurizr renderer on the structurizr server supports the icons of the theme I am searching for other alternatives like this one.

**Comment by MTomBosch** [comment]
> 
> 
> The C4 PlantUML project also allows setting icons from external URLs, e.g. to add the Java icon. It would be great to also allow using those if this feature is implemented.

I was not aware of this feature, yet. Nice.

**Comment by simonbrowndotje** [comment]
> Since only the structurizr renderer on the structurizr server supports the icons of the theme I am searching for other alternatives like this one.

You don't like how Structurizr renders diagrams?

**Comment by MLNW** [comment]
> 
> 
> > Since only the structurizr renderer on the structurizr server supports the icons of the theme I am searching for other alternatives like this one.
> 
> You don't like how Structurizr renders diagrams?

For me its simply a matter of accessibility. Yes, I like how the online version of Structurizr renders diagrams but for my use case it has to be offline either as part of a script or deployment pipeline.

Therefore, I use the PlantUML export and there the C4-PlantUML project just renders nicer-looking diagrams. It also does offer some more customization, though most of it I have to do manually after exporting the workspace. It shouldn't be too hard to improve those things though.

**Comment by simonbrowndotje** [comment]
> Yes, I like how the online version of Structurizr renders diagrams but for my use case it has to be offline either as part of a script or deployment pipeline.

The [on-premises installation](https://structurizr.com/help/on-premises) (free and paid) in combination with some [Puppeteer scripts](https://github.com/structurizr/puppeteer) allow you to achieve both offline use, and integration with a deployment pipeline. There's also now a [Structurizr Lite](https://structurizr.com/help/lite) (free) version for even easier offline use.

**Comment by MLNW** [comment]
> The [on-premises installation](https://structurizr.com/help/on-premises) (free and paid) in combination with some [Puppeteer scripts](https://github.com/structurizr/puppeteer) allow you to achieve both offline use, and integration with a deployment pipeline. There's also now a [Structurizr Lite](https://structurizr.com/help/lite) (free) version for even easier offline use.

Interesting. I'm quite far down the road now though and do not have time to try it out. The deadline for my thesis is fast approaching and I still have a heap of other things to tend to 😉

**Comment by MTomBosch** [comment]
> 
> 
> > Since only the structurizr renderer on the structurizr server supports the icons of the theme I am searching for other alternatives like this one.
> 
> You don't like how Structurizr renders diagrams?

I like it a lot but just as MLNW would need an offline version of this feature. I will check your proposal.
Thank you

**Comment by simonbrowndotje** [comment]
> I'm quite far down the road now though and do not have time to try it out.

If you're using the DSL and have Docker already installed, you can be up and running in <5 minutes ... see [Getting started with Structurizr Lite](https://dev.to/simonbrown/getting-started-with-structurizr-lite-27d0).

If you're using the Java client library, add the following lines to your program (change `/some/path` to be the directory that Structurizr Lite is looking at), and follow the same instructions in the getting started guide, ignoring anything about the DSL file:

```
workspace.getViews().getViews().forEach(View::enableAutomaticLayout);
WorkspaceUtils.saveWorkspaceToJson(workspace, new File("/some/path/workspace.json"));
```

**Comment by MTomBosch** [comment]
Hi Simon,
I have one more idea how this could be achieved with medium/small effort from your and my side without the need for the structurizr lite docker image and some curl/pupeteer scripts or Java.

If you could add the dsl defined element tags as $tags in the C4PlantUML elements, e.g. look at this small example:

```
Person(user, "Customer", "People that need products")
Person(admin, "Administrator", "People that administrates the products via the new v1.1 components", $tags="v1.1")
Container(spa, "SPA", "angular", "The main interface that the customer interacts with via v1.0", $tags="v1.0")
Container(spaAdmin, "Admin SPA", "angular", "The administrator interface that the customer interacts with via new v1.1", $tags="v1.1")
Container(api, "API", "java", "Handles all business logic (incl. new v1.1 extensions)", $tags="v1.0+v1.1")
ContainerDb(db, "Database", "Microsoft SQL", "Holds product, order and invoice information")
Container(archive, "Archive", "Audit logging", "Stores 5 years", $tags="backup")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Uses", "https")
Rel_R(api, db, "Reads/Writes")
Rel(admin, spaAdmin, "Uses", "https")
Rel(spaAdmin, api, "Uses", "https")
Rel_L(api, archive, "Writes", "messages", $tags="backup")

```

Then I could easily write some post-processing script that adds statements like below to the generated plantuml files:

```
AddElementTag("v1.0", $borderColor="#d73027")
AddElementTag("v1.1", $fontColor="#d73027")
AddElementTag("backup", $fontColor="orange")

AddRelTag("backup", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())

```

The final puml file would then look like this: 

```
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("v1.0", $borderColor="#d73027")
AddElementTag("v1.1", $fontColor="#d73027")
AddElementTag("backup", $fontColor="orange")

AddRelTag("backup", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())

Person(user, "Customer", "People that need products")
Person(admin, "Administrator", "People that administrates the products via the new v1.1 components", $tags="v1.1")
Container(spa, "SPA", "angular", "The main interface that the customer interacts with via v1.0", $tags="v1.0")
Container(spaAdmin, "Admin SPA", "angular", "The administrator interface that the customer interacts with via new v1.1", $tags="v1.1")
Container(api, "API", "java", "Handles all business logic (incl. new v1.1 extensions)", $tags="v1.0+v1.1")
ContainerDb(db, "Database", "Microsoft SQL", "Holds product, order and invoice information")
Container(archive, "Archive", "Audit logging", "Stores 5 years", $tags="backup")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Uses", "https")
Rel_R(api, db, "Reads/Writes")
Rel(admin, spaAdmin, "Uses", "https")
Rel(spaAdmin, api, "Uses", "https")
Rel_L(api, archive, "Writes", "messages", $tags="backup")

SHOW_LEGEND()
@enduml

```

**Comment by simonbrowndotje** [comment]
This is now live on the [DSL demo page](https://structurizr.com/dsl), and I decided to export all tags for every element/relationship. To make things easier for you to extend the output, I've also added a way to customise the PlantUML export ... for example, if you wanted to add all of your tag definitions into a separate file named `styles.puml`, you can do something like this:

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout
        }

        properties {
            "plantuml.includes" "styles.puml"
        }
    }
    
}
```

This will create the following PlantUML output:

```
@startuml
title Software System - System Context

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include styles.puml

Person(User, "User", "", $tags="Element,Person")
System(SoftwareSystem, "Software System", "", $tags="Element,Software System")

Rel_D(User, SoftwareSystem, "Uses", $tags="Relationship")

SHOW_LEGEND()
@enduml
```

If you'd like to disable the legend and use your own, you can use the `plantuml.legend` property (set to `false`) too.

**Comment by MTomBosch** [comment]
I really don't know what to say. I guess this is my Christmas present :)

Thanks a lot.

I will do some testing on the demo page the next few days.

**Comment by MTomBosch** [comment]
Wrt to the legend it works fine. I cannot test the include puml feature though since on the demo page there is no puml file available that can be included.
Whenever you release it I will do my testing then.

**Comment by simonbrowndotje** [comment]
Just create yourself a gist and use the URL to the raw content; for example:

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout
        }
        
        properties {
            "plantuml.includes" "https://gist.githubusercontent.com/simonbrowndotje/b84878f8b87af3b76753ed871611c700/raw/b659b7ab9ac02a04725606f59138f37d2e67c265/styles.puml"
        }
    }
    
}
```

**Comment by MTomBosch** [comment]
Ahh ok. Did not know the "includes" property support a http adress as well.
Fine will do it.

**Comment by MTomBosch** [comment]
Works nicely, thank you.
I just noticed that now the C4 stereotype is visible (which was the case already before this change) but also the added tags are now visible as well as additional stereo types on the elements. I will see if this can be somehow disabled in C4 since it is kind of redundant in the diagram and will reply the necessary changes.

**Comment by MTomBosch** [comment]
One thing I already found out is that tags in C4Plantuml are not divided by a comma "," but by a plus "+". Would be cool to fix that in your implementation.

`Each element can be extended with one or multiple custom tags via the keyword argument $tags="...", like Container(spaAdmin, "Admin SPA", $tags="v1.1"). Multiple tags can be combined with +, like Container(api, "API", $tags="v1.0+v1.1").`

**Comment by simonbrowndotje** [comment]
> tags in C4Plantuml are not divided by a comma "," but by a plus "+".

Thanks, that should now be working on the demo page.

**Comment by MTomBosch** [comment]
> Works nicely, thank you. I just noticed that now the C4 stereotype is visible (which was the case already before this change) but also the added tags are now visible as well as additional stereo types on the elements. I will see if this can be somehow disabled in C4 since it is kind of redundant in the diagram and will reply the necessary changes.

I found the reason for this behaviour. If the legend is not shown then all tags (the implicit ones from the C4 model type and the explicit ones) are always shown. If the legend is enabled then the tags are no more visible in the shape text.

Since the styling now works perfectly I will close the issue.

Thank you and I wish you happy holidays.
