### ISSUE TITLE
Protected methods of PlantUmlWriter gone package protected on structurizr-plantuml >= 1.4

### ISSUE THREAD

**Issue by odrotbohm** [structurizr/java-extensions#55]
I would like to add C4 component diagram support to Moduliths and thought I'd upgrade to a recent `structurizr-plantuml`. It turns out I have to stay with 1.3.8 as in 1.4, some methods, that had been protected have turned into package protected ones. In particular, I was using the `backgroundOf(…)` method to color a subset of components rendered based on some external settings.

Any chance those methods are made protected again? I am aware of the move to `structurizr-export` as new API, but that currently doesn't seem to support classic UML component diagram rendering right now (separate ticket coming), and I need that for backwards compatibility purposes.

**Comment by simonbrowndotje** [comment]
The way to do this with the newer versions would be to:

1. Add a tag to each of those components.
2. Create an element style for that tag, with the required background colour.

The framework should then take care of everything for you, without the need to override any methods.

**Comment by odrotbohm** [comment]
That does help indeed. I could upgrade to the latest versions of the `structurizr-plantuml` artifact using that. One question though: the output is now plain rectangles instead of native component shapes. It looks like this is due to `Styles.findElementStyle(…)` defaulting to `Shape.Box` independent of the `Element`'s actual type. Does it make sense to switch to the "component" stencil for those?

I've tried to customize that myself, but the `Styles` API is not the most easy  one to work with. You can register styles for a certain tag, but double registrations are rejected. However, there's no way to lookup the style potentially already associated with a tag. Also, `findElementStyle(Element)` doesn't really "find" any registered ones but creates new ones on the fly. So even if you look up the one for components for example, and add it to the `Styles`, they'll never get actually used as `PlantUMLWriter.plantUMLShapeOf(…)` just uses `findElementStyle(…)` which in turn creates fresh instances. So it's not really obvious how you'd customize the style for a particular element.

**Comment by simonbrowndotje** [comment]
To get coloured component shapes rather then rectangles, something like this should work:

```
workspace.getViews().getConfiguration().getStyles().addElementStyle(Tags.COMPONENT).shape(Shape.Component);
workspace.getViews().getConfiguration().getStyles().addElementStyle("your tag").background("#aabbcc");

BasicPlantUMLWriter writer = new BasicPlantUMLWriter();
writer.addSkinParam("componentStyle", "uml1");

writer...
```

**Comment by odrotbohm** [comment]
Lovely, thanks, that did the trick! 🙇
