### ISSUE TITLE
Exported Mermaid Code has Syntax Issues 

### ISSUE THREAD

**Issue by Jugo84** [structurizr/java-extensions#57]
It looks like the exported mermaid code has syntax issues or it's a set of mermaid setttings i'm not able to figure out to get it working? Double checked with the mermaid code of one of your unit tests, but it's not working as well. 
I have played a little bit with that mermaid code around and it looks like the inline-styles in the div's are causing the issues...

**Comment by simonbrowndotje** [comment]
The examples work for me with the live editor ([example](https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoiZ3JhcGggVEJcbiAgbGlua1N0eWxlIGRlZmF1bHQgZmlsbDojZmZmZmZmXG5cbiAgMVtcIjxkaXYgc3R5bGU9J2ZvbnQtd2VpZ2h0OiBib2xkJz5Vc2VyPC9kaXY-PGRpdiBzdHlsZT0nZm9udC1zaXplOiA3MCU7IG1hcmdpbi10b3A6IDBweCc-W1BlcnNvbl08L2Rpdj5cIl1cbiAgc3R5bGUgMSBmaWxsOiMwODQyN2Isc3Ryb2tlOiMwNTJlNTYsY29sb3I6I2ZmZmZmZlxuICAyKFwiPGRpdiBzdHlsZT0nZm9udC13ZWlnaHQ6IGJvbGQnPlNvZnR3YXJlIFN5c3RlbTwvZGl2PjxkaXYgc3R5bGU9J2ZvbnQtc2l6ZTogNzAlOyBtYXJnaW4tdG9wOiAwcHgnPltTb2Z0d2FyZSBTeXN0ZW1dPC9kaXY-XCIpXG4gIHN0eWxlIDIgZmlsbDojMTE2OGJkLHN0cm9rZTojMGI0ODg0LGNvbG9yOiNmZmZmZmZcblxuICAxLS4gXCI8ZGl2PlVzZXM8L2Rpdj48ZGl2IHN0eWxlPSdmb250LXNpemU6IDcwJSc-PC9kaXY-XCIgLi0-MiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCIsXG4gIFwic2VjdXJpdHlMZXZlbFwiOiBcImxvb3NlXCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)) ... HTML tags in Mermaid require the addition of `"securityLevel": "loose"`.

**Comment by Jugo84** [comment]
Sorry it was a false positive. There's a problem somewhere at mermaid initialization. Thanks.
