### ISSUE TITLE
Suggestion to add export to diagrams.net

### ISSUE THREAD

**Issue by souliane** [structurizr/java-extensions#63]
Hi,

The company I am working in uses the `diagrams.net` plugin for `Confluence` to architect IT systems.
I am willing to use `structurizr`, and trying to make my colleagues try it out.
The problem is that 1. they are used to `diagrams.net` and 2. not everybody like the "diagrams as text/code" approach.

It is good that `structurizr` output can be integrated to `Confluence`, but for my colleagues, if it's not done with `diagrams.net`, a dynamic diagram or a static image is the same. I feel the need for a `structurizr --> diagrams.net` exporter (IFAIK that is SVG + metadata for the relationships), so that I can work with `structurizr` and then embed `diagrams.net` canvases to `Confluence`. Note that there's already a (rudimentary) C4 support in `diagrams.net`: https://www.diagrams.net/blog/c4-modelling

Ideally, the conversion would be bidirectional but I guess that this would be quite difficult to implement... to be able to convert from `structurizr` to `diagrams.net` would already be a great achievement.

Cheers,
Adrien

**Comment by simonbrowndotje** [comment]
I have no plans to build a diagrams.net export myself, but [this blog post](https://www.diagrams.net/blog/insert-from-csv) may provide some inspiration if you'd like to do it yourself.

**Comment by souliane** [comment]
Thanks for the info, I might actually do it.

**Comment by souliane** [comment]
Hi Simon, FYI I have released here a Python package to convert structurizr DSL/JSON to diagrams.net CSV: https://gitlab.com/souliane/structurizr2csv/

**Comment by simonbrowndotje** [comment]
That's great! 👏 I'll add a link to your repo from a few places...
